version: '3'
services:
  postgres:
    container_name: data-warehouse
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=udacity
      - POSTGRES_PASSWORD=udacity
      - POSTGRES_DB=capstone_project
    ports:
      - 5432:5432
    networks:
      udacity_network:
          ipv4_address: 172.28.1.2

  datascience-notebook:
    container_name: visual-analytics
    image: jupyter/datascience-notebook
    volumes:
      - "./notebooks:/home/jovyan/notebooks"
    ports:
      - 8888:8888
    networks:
      udacity_network:
          ipv4_address: 172.28.1.3

  airflow-spark245:
    container_name: data-engineering
    depends_on:
      - postgres
      - datascience-notebook
    build: .
    networks:
      udacity_network:
          ipv4_address: 172.28.1.1

networks:
  udacity_network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
